### ISSUE TITLE
Refactor to use navigation component

### ISSUE THREAD

**Issue by BillyLuisNeedham** [BillyLuisNeedham/Fruit-Displayer#19]
## Todo
- [x] create nav graph
- [x] update fragments to use safe args
- [x] refactor tests as required
- [x] implement in activity
